services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: appPresupuestoSqlServer
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass@12345
      - MSSQL_PID=Developer
      - MSSQL_MEMORY_LIMIT_MB=2048 
    deploy:
      resources:
        limits:
          memory: 2500M
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - budget_network
    restart: always

volumes:
  sql_data:

networks:
  budget_network:
    driver: bridge